package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strings"
)

// opencodeModelEntry represents a single model inside an opencode provider config.
type opencodeModelEntry struct {
	ID    string             `json:"id"`
	Limit opencodeModelLimit `json:"limit"`
}

type opencodeModelLimit struct {
	Context int `json:"context"`
	Input   int `json:"input"`
	Output  int `json:"output"`
}

// opencodeProviderOptions holds connection options for a provider.
type opencodeProviderOptions struct {
	BaseURL string `json:"baseURL"`
	APIKey  string `json:"apiKey"`
}

// opencodeProviderConfig represents a provider in the opencode config.
type opencodeProviderConfig struct {
	API     string                        `json:"api"`
	Name    string                        `json:"name"`
	Options opencodeProviderOptions       `json:"options"`
	Models  map[string]opencodeModelEntry `json:"models"`
}

// opencodeConfig is the top-level structure generated for opencode.jsonc.
// It follows the schema at https://opencode.ai/config.json.
type opencodeConfig struct {
	Schema           string                            `json:"$schema"`
	EnabledProviders []string                          `json:"enabled_providers"`
	Provider         map[string]opencodeProviderConfig `json:"provider"`
}

// defaultGenerationLimit is the max tokens per generation when using llm-bridge models.
const defaultGenerationLimit = 3000

// defaultMaxModelLen is used when the upstream model metadata has no max_model_len.
const defaultMaxModelLen = 8192

// defaultProviderName is the single provider name used for all llm-bridge models.
const defaultProviderName = "llm-bridge"

// handleOpenCodeConfig generates an opencode.jsonc configuration with all discovered
// models, their context limits derived from upstream metadata, and enables only the
// "llm-bridge" provider (all external providers are implicitly disabled).
func (s *Server) handleOpenCodeConfig(w http.ResponseWriter, r *http.Request) {
	baseURL := r.URL.Query().Get("base_url")
	cfg := s.cfg.Get()
	if baseURL == "" {
		baseURL = cfg.Global.OpenCodeBaseURL
	}
	if baseURL == "" {
		scheme := "http"
		if r.TLS != nil {
			scheme = "https"
		}
		baseURL = scheme + "://" + r.Host
	}

	// Append /v1 so opencode sends requests to llm-bridge's OpenAI-compatible API path.
	baseURL = strings.TrimRight(baseURL, "/") + "/v1"

	models := s.disc.Models()
	details := s.disc.ModelDetails()

	modelNames := make([]string, 0, len(models))
	for name := range models {
		modelNames = append(modelNames, name)
	}
	sort.Strings(modelNames)

	// Build model entries inside the single llm-bridge provider.
	buffer := cfg.Global.OpenCodeContextBuffer
	input := cfg.Global.OpenCodeContextInput

	modelEntries := make(map[string]opencodeModelEntry, len(modelNames))
	for _, name := range modelNames {
		ctx := extractMaxModelLen(details[name])

		var outLimit, inLimit int

		if input == 0 {
			// Auto mode: output fixed at 3000, input = buffer - 3000
			outLimit = 3000
			inLimit = buffer - outLimit
		} else {
			// Explicit mode: output = buffer - input
			outLimit = buffer - input
			inLimit = input
		}

		// Apply guards
		if inLimit < 1000 {
			inLimit = 1000
		}
		if outLimit < 3000 {
			outLimit = 3000
		}

		modelEntries[name] = opencodeModelEntry{
			ID: name,
			Limit: opencodeModelLimit{
				Context: ctx,
				Input:   inLimit,
				Output:  outLimit,
			},
		}
	}

	oc := opencodeConfig{
		Schema:           "https://opencode.ai/config.json",
		EnabledProviders: []string{defaultProviderName},
		Provider: map[string]opencodeProviderConfig{
			defaultProviderName: {
				API:  "openai",
				Name: defaultProviderName,
				Options: opencodeProviderOptions{
					BaseURL: baseURL,
					APIKey:  "sk-llm-bridge",
				},
				Models: modelEntries,
			},
		},
	}

	raw, err := json.MarshalIndent(oc, "", "  ")
	if err != nil {
		s.respondError(w, http.StatusInternalServerError, "failed to generate config")
		return
	}

	comment := fmt.Sprintf(`// Auto-generated by llm-bridge
// Only the %q provider is enabled — all external providers are implicitly disabled.
// Set "baseURL" below to match your llm-bridge address if different.

%s`, defaultProviderName, string(raw))

	w.Header().Set("Content-Type", "application/jsonc")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write([]byte(comment)); err != nil {
		s.respondError(w, http.StatusInternalServerError, "failed to write response")
		return
	}
}

// extractMaxModelLen attempts to parse the raw model metadata to find the
// upstream model's maximum context length. It checks common field names used
// by vLLM, OpenAI, and other providers.
func extractMaxModelLen(raw json.RawMessage) int {
	if len(raw) == 0 {
		return defaultMaxModelLen
	}

	var meta struct {
		MaxModelLen   int `json:"max_model_len"`
		MaxTokens     int `json:"max_tokens"`
		ContextLen    int `json:"context_length"`
		MaxContextLen int `json:"max_context_length"`
	}
	if err := json.Unmarshal(raw, &meta); err != nil {
		return defaultMaxModelLen
	}

	switch {
	case meta.MaxModelLen > 0:
		return meta.MaxModelLen
	case meta.MaxContextLen > 0:
		return meta.MaxContextLen
	case meta.MaxTokens > 0:
		return meta.MaxTokens + defaultGenerationLimit
	case meta.ContextLen > 0:
		return meta.ContextLen
	default:
		return defaultMaxModelLen
	}
}
