package server

import (
	"encoding/json"
	"io"
	"fmt"
	"net/http"
	"sort"
	"strings"
)

// opencodeModelEntry represents a single model inside an opencode provider config.
type opencodeModelEntry struct {
	ID    string             `json:"id"`
	Limit opencodeModelLimit `json:"limit"`
}

type opencodeModelLimit struct {
	Context int `json:"context"`
	Input   int `json:"input"`
	Output  int `json:"output"`
}

// opencodeProviderOptions holds connection options for a provider.
type opencodeProviderOptions struct {
	BaseURL string `json:"baseURL"`
	APIKey  string `json:"apiKey"`
}

// opencodeProviderConfig represents a provider in the opencode config.
type opencodeProviderConfig struct {
	API     string                        `json:"api"`
	Name    string                        `json:"name"`
	Options opencodeProviderOptions       `json:"options"`
	Models  map[string]opencodeModelEntry `json:"models"`
}

// opencodeConfig is the top-level structure generated for opencode.jsonc.
// It follows the schema at https://opencode.ai/config.json.
type opencodeConfig struct {
	Schema           string                            `json:"$schema"`
	EnabledProviders []string                          `json:"enabled_providers"`
	Provider         map[string]opencodeProviderConfig `json:"provider"`
}

// defaultGenerationLimit is the max tokens per generation when using llm-bridge models.
const defaultGenerationLimit = 3000

// defaultMaxModelLen is used when the upstream model metadata has no max_model_len.
const defaultMaxModelLen = 8192

// defaultProviderName is the single provider name used for all llm-bridge models.
const defaultProviderName = "llm-bridge"

// extractMaxModelLen attempts to parse the raw model metadata to find the
// upstream model's maximum context length. It checks common field names used
// by vLLM, OpenAI, and other providers.
func extractMaxModelLen(raw json.RawMessage) int {
	if len(raw) == 0 {
		return defaultMaxModelLen
	}

	var meta struct {
		MaxModelLen   int `json:"max_model_len"`
		MaxTokens     int `json:"max_tokens"`
		ContextLen    int `json:"context_length"`
		MaxContextLen int `json:"max_context_length"`
	}
	if err := json.Unmarshal(raw, &meta); err != nil {
		return defaultMaxModelLen
	}

	switch {
	case meta.MaxModelLen > 0:
		return meta.MaxModelLen
	case meta.MaxContextLen > 0:
		return meta.MaxContextLen
	case meta.MaxTokens > 0:
		return meta.MaxTokens + defaultGenerationLimit
	case meta.ContextLen > 0:
		return meta.ContextLen
	default:
		return defaultMaxModelLen
	}
}


// resolveBaseURL determines the base URL for llm-bridge:
// 1. from the query parameter (if non-empty),
// 2. from the config's OpenCodeBaseURL,
// 3. auto-detected from the request (scheme + host).
// Finally it appends "/v1".
func (s *Server) resolveBaseURL(r *http.Request, queryBaseURL string) string {
	baseURL := queryBaseURL
	if baseURL == "" {
		baseURL = s.cfg.Get().Global.OpenCodeBaseURL
	}
	if baseURL == "" {
		scheme := "http"
		if r.TLS != nil {
			scheme = "https"
		}
		baseURL = scheme + "://" + r.Host
	}
	return strings.TrimRight(baseURL, "/") + "/v1"
}

// buildModelEntries builds the per-model entries for the opencode provider.
func (s *Server) buildModelEntries() map[string]opencodeModelEntry {
	models := s.disc.Models()
	details := s.disc.ModelDetails()

	modelNames := make([]string, 0, len(models))
	for name := range models {
		modelNames = append(modelNames, name)
	}
	sort.Strings(modelNames)

	buffer := s.cfg.Get().Global.OpenCodeContextBuffer
	input := s.cfg.Get().Global.OpenCodeContextInput

	entries := make(map[string]opencodeModelEntry, len(modelNames))
	for _, name := range modelNames {
		ctx := extractMaxModelLen(details[name])

		inLimit := input
		if inLimit == 0 {
			inLimit = buffer
		}
		if inLimit > ctx {
			inLimit = ctx / 4
		}
		outLimit := ctx - inLimit
		if outLimit < 1000 {
			outLimit = 1000
		}

		entries[name] = opencodeModelEntry{
			ID: name,
			Limit: opencodeModelLimit{
				Context: ctx,
				Input:   inLimit,
				Output:  outLimit,
			},
		}
	}
	return entries
}

// generateOpenCodeConfig creates the opencode.jsonc structure with all discovered
// models and the single "llm-bridge" provider enabled. It returns the JSON bytes
// and the header comment block.
func (s *Server) generateOpenCodeConfig(baseURL string) ([]byte, string, error) {
	modelEntries := s.buildModelEntries()

	oc := opencodeConfig{
		Schema:           "https://opencode.ai/config.json",
		EnabledProviders: []string{defaultProviderName},
		Provider: map[string]opencodeProviderConfig{
			defaultProviderName: {
				API:  "openai",
				Name: defaultProviderName,
				Options: opencodeProviderOptions{
					BaseURL: baseURL,
					APIKey:  "sk-llm-bridge",
				},
				Models: modelEntries,
			},
		},
	}

	raw, err := json.MarshalIndent(oc, "", "  ")
	if err != nil {
		return nil, "", fmt.Errorf("marshal config: %w", err)
	}

	comment := fmt.Sprintf(`// Auto-generated by llm-bridge
// Only the %q provider is enabled — all external providers are implicitly disabled.
// Set "baseURL" below to match your llm-bridge address if different.

%s`, defaultProviderName, string(raw))

	return raw, comment, nil
}

// stripJSONC removes single-line comments (// ...) from JSONC content.
// It preserves strings (doesn't remove // inside quoted values) and
// handles multi-line strings minimally by only stripping // outside quotes.
func stripJSONC(data string) string {
	var result strings.Builder
	lines := strings.Split(data, "\n")
	for _, line := range lines {
		result.WriteString(stripLineComment(line))
		result.WriteString("\n")
	}
	return strings.TrimRight(result.String(), "\n")
}

// stripLineComment removes the // comment portion from a single line,
// respecting string literals.
func stripLineComment(line string) string {
	inString := false
	escape := false
	for i := 0; i < len(line); i++ {
		ch := line[i]
		if escape {
			escape = false
			continue
		}
		if ch == '\\' && inString {
			escape = true
			continue
		}
		if ch == '"' {
			inString = !inString
			continue
		}
		if !inString && i+1 < len(line) && ch == '/' && line[i+1] == '/' {
			return line[:i]
		}
	}
	return line
}

// handleOpenCodeConfig generates an opencode.jsonc configuration with all discovered
// models, their context limits derived from upstream metadata, and enables only the
// "llm-bridge" provider (all external providers are implicitly disabled).
func (s *Server) handleOpenCodeConfig(w http.ResponseWriter, r *http.Request) {
	baseURL := s.resolveBaseURL(r, r.URL.Query().Get("base_url"))

	_, comment, err := s.generateOpenCodeConfig(baseURL)
	if err != nil {
		s.respondError(w, http.StatusInternalServerError, err.Error())
		return
	}

	w.Header().Set("Content-Type", "application/jsonc")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write([]byte(comment)); err != nil {
		s.respondError(w, http.StatusInternalServerError, "failed to write response")
		return
	}
}

// handlePostOpenCodeConfig accepts a user's current opencode.jsonc, strips comments,
// parses it, and returns a fresh working configuration with the llm-bridge provider.
func (s *Server) handlePostOpenCodeConfig(w http.ResponseWriter, r *http.Request) {
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		s.respondError(w, http.StatusBadRequest, "failed to read request body")
		return
	}

	content := strings.TrimSpace(string(bodyBytes))
	if content == "" {
		s.respondError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}

	// Strip JSONC comments if present.
	if strings.Contains(content, "//") {
		content = stripJSONC(content)
	}
	content = strings.TrimSpace(content)

	// Parse as generic JSON.
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		s.respondError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}

	// Extract context limits from the user's config if present.
	// Check nested structures: provider["provider-name"]["models"] or top-level.
	buffer := s.cfg.Get().Global.OpenCodeContextBuffer
	input := s.cfg.Get().Global.OpenCodeContextInput

	// Try to find context limits in the parsed config.
	if models, ok := parsed["models"].(map[string]interface{}); ok {
		for _, modelData := range models {
			if md, ok := modelData.(map[string]interface{}); ok {
				if l, ok := md["limit"].(map[string]interface{}); ok {
					if inp, ok := l["input"].(float64); ok && inp > 0 {
						input = int(inp)
					}
					if ctx, ok := l["context"].(float64); ok {
						_ = ctx // context from user config is informational only
					}
				}
			}
		}
	}

	// Override buffer/input if explicitly set in config.
	if cfg := s.cfg.Get(); cfg.Global.OpenCodeContextInput > 0 {
		input = cfg.Global.OpenCodeContextInput
	}
	if cfg := s.cfg.Get(); cfg.Global.OpenCodeContextBuffer > 0 {
		buffer = cfg.Global.OpenCodeContextBuffer
	}

	// Build model entries with the (potentially user-derived) limits.
	models := s.disc.Models()
	details := s.disc.ModelDetails()

	modelNames := make([]string, 0, len(models))
	for name := range models {
		modelNames = append(modelNames, name)
	}
	sort.Strings(modelNames)

	modelEntries := make(map[string]opencodeModelEntry, len(modelNames))
	for _, name := range modelNames {
		ctx := extractMaxModelLen(details[name])

		inLimit := input
		if inLimit == 0 {
			inLimit = buffer
		}
		if inLimit > ctx {
			inLimit = ctx / 4
		}
		outLimit := ctx - inLimit
		if outLimit < 1000 {
			outLimit = 1000
		}

		modelEntries[name] = opencodeModelEntry{
			ID: name,
			Limit: opencodeModelLimit{
				Context: ctx,
				Input:   inLimit,
				Output:  outLimit,
			},
		}
	}

	// Get base URL.
	baseURL := s.resolveBaseURL(r, r.URL.Query().Get("base_url"))

	oc := opencodeConfig{
		Schema:           "https://opencode.ai/config.json",
		EnabledProviders: []string{defaultProviderName},
		Provider: map[string]opencodeProviderConfig{
			defaultProviderName: {
				API:  "openai",
				Name: defaultProviderName,
				Options: opencodeProviderOptions{
					BaseURL: baseURL,
					APIKey:  "sk-llm-bridge",
				},
				Models: modelEntries,
			},
		},
	}

	raw, err := json.MarshalIndent(oc, "", "  ")
	if err != nil {
		s.respondError(w, http.StatusInternalServerError, "failed to generate config")
		return
	}

	comment := fmt.Sprintf(`// Auto-generated by llm-bridge
// Only the %q provider is enabled — all external providers are implicitly disabled.
// Set "baseURL" below to match your llm-bridge address if different.

%s`, defaultProviderName, string(raw))

	w.Header().Set("Content-Type", "application/jsonc")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write([]byte(comment)); err != nil {
		s.respondError(w, http.StatusInternalServerError, "failed to write response")
		return
	}
}

